modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="magistuarmory" #mandatory
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Epic Knights: Armor and Weapons" #mandatory
logoFile="examplemod.png" #optional
authors="Magistu" #optional
credits=["StaxiHD", "Mino", "Jackiecrazy"] #optional
description='''
Adds late medieval armor and weapons.
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"